travis:
  secure:
    BINSTAR_TOKEN: R6yUUrvVMb0rePp4bI2vwOcXUcL/DzysSAudC4FuRgMNVbheqw/gIGbWO+YGHDK42QA3jlPGLDEPeLyx8GWxHTG/TAGkXAuo/ssC0yMqLdklDiEvLYMH5M+YqF3NEQMy5xlGaIngACVPPDoRgb01KvUicNP+PdhNhOiQ1QBAHUahjsOQh8y9fIY9G+zDsfOarYOgjUnOJItPGHncVSn3FlutRdqrFq2Hhhap0jtXpXjvH3w4fyWuLGXhMfy1Zjn99K1KQJCW7GBzh8BVJKMtNxiDU2HTgW3gglwor1ONrtYPzOXkuSuMQ+Ob9lREo+BOi3oYJ20HNZG3VC9SH9HqZZLcw4IgZeFbYnweNip5TgU+EZJ3mtmi+6QxF/0nuQNnOFVc8VFUj1UDIoJybrjIZokR/w7fkhmoDz5KyHA/8w8NMmYPaIyjATejNoIRz/aqLUpZn4D5MRQ8PomghV9EfzxAIXHLSTpVNv9DtZFMlEtDeF8qXeKYTMnL2ak6oYsGBgSHXfF6VTXcziygDdtNi6Jz8liaPRansN9uXhQDWRsPItZs6uv1qKzkgFbgA91mv7pQWwRZLMJ+8vAdkZsyeJsmoJGHA3klKoAihF040tqOGr3FwkWUhNjkbzNpOajm/dM+IB3ytzzHGsfx37PrzqleMzxXJyFXOcMe7ze8VOA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
